### ISSUE TITLE
dpgen2 can not support CP2K

### ISSUE THREAD

**Issue by smclucky** [deepmodeling/dpgen2#180]
I attempted to utilize the CP2K package for implementing DPGEN2, but encountered the following error: 

```
raise ArgumentValueError(
dargs.dargs.ArgumentValueError: [at location `fp`] get invalid choice `cp2k` for flag key `type`.
```

It would be greatly beneficial if the developer could provide support for CP2K in DPGEN2, as CP2K is a valuable tool.

**Comment by zjgemi** [comment]
https://github.com/deepmodeling/dpgen2/pull/238
