### ISSUE TITLE
dpgen2 showkey seems not work at debug mode

### ISSUE THREAD

**Issue by scott-5** [deepmodeling/dpgen2#192]
`urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=2746): Max retries exceeded with url: /api/v1/workflows/argo/dpgen-f05hl/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2b372af03cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))`

**Comment by zjgemi** [comment]
The issue should be solved for pydflow>=1.8.49.

**Comment by scott-5** [comment]
Thank you so much. Now it can run normally.
