### ISSUE TITLE
可否提供dpgen2  slurm调用示例

### ISSUE THREAD

**Issue by Tengfei9228** [deepmodeling/dpgen2#235]
可否提类似dpgen中基于slurm 的machine.json 配置示例

**Comment by wanghan-iapcm** [comment]
we do not accept Chinese issues.

**Comment by KK33999** [comment]
Dear developers, I have also encountered the same problem. May I ask if dpgen2 can run on the Slurm queue and if you can provide a template for environment configuration parameters such as "step_comfigs". Thanks in advance.
