### ISSUE TITLE
CH4 example needs update

### ISSUE THREAD

**Issue by wanghan-iapcm** [deepmodeling/dpgen2#66]
Some of the keys in the input file `example/ch4/param_CH4_deepmd-kit-2.0.1.json` are outdated. For example `run_fp_image` is not supported anymore. We need to update the input file

**Comment by njzjz** [comment]
Where is `example/ch4/param_CH4_deepmd-kit-2.0.1.json`? I can't find it anywhere.

**Comment by HuangJiameng** [comment]
I wonder if you mean `example/ch4/param_CH4_deepmd-kit-2.1.1.json`?

**Comment by wanghan-iapcm** [comment]
closed via #67
