### ISSUE TITLE
read the doc for dpgen2

### ISSUE THREAD

**Issue by wanghan-iapcm** [deepmodeling/dpgen2#72]
The dpgen2 project needs a readthedoc page for documentation

**Comment by njzjz** [comment]
I created one, but I don't have access to the automatic build. If you have readthedoc account I can add you as the maintainer.

https://readthedocs.org/projects/dpgen2/

**Comment by njzjz** [comment]
Documentation built on https://docs.deepmodeling.com/projects/dpgen2/
